# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: windows-latest

parameters:
- name: configs
  type: string
  values:
    - qa
    - dev
    - prod

trigger: none
stages:
  - stage: one
    jobs:
      - ${{ if contains(parameters.configs, 'dev') }}:
      - job: one
        pool:
          vmImage: 'windows-latest'
        steps:
        -   script: echo hello from Windows
                
          #         echo 'Hello dev'
          # - task: TriggerPipeline@2
          #   inputs:
          #     serviceConnection: 'second-connection'
          #     project: 'e5edbb49-5652-4c20-906c-a0269b1c9c91'
          #     Pipeline: 'Build'
          #     buildDefinition: '3'
          #     Branch: 'main'
          #     buildapiversion: '6.0'
     
      
    
      # - ${{ if contains(parameters.configs, 'prod') }}:
      # - job: prod
      #   pool:
      #       vmImage: 'windows-latest'
      #   steps:
      #   - script: echo hello from Window
