# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

stages:
  - stage: one
    jobs:
      - job: one
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                echo 'Hello stage one'
    
  - stage: two
    jobs:
      - job: two
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                echo 'Hello stage two'
          
          - task: TriggerBuild@4
            inputs:
              definitionIsInCurrentTeamProject: true
              buildDefinition: 'param'
              queueBuildForUserThatTriggeredBuild: false
              ignoreSslCertificateErrors: false
              useSameSourceVersion: false
              useCustomSourceVersion: false
              useSameBranch: true
              waitForQueuedBuildsToFinish: false
              storeInEnvironmentVariable: false
              buildParameters: 'dev'
              authenticationMethod: 'Personal Access Token'
              enableBuildInQueueCondition: false
              dependentOnSuccessfulBuildCondition: false
              dependentOnFailedBuildCondition: false
              checkbuildsoncurrentbranch: false
              failTaskIfConditionsAreNotFulfilled: false
          
          # - task: pipeline-triggerer-task@0
          #   inputs:
          #     adoServiceConnection: 'serv-conn-one'
          #     Project: 'e5edbb49-5652-4c20-906c-a0269b1c9c91'
          #     PipelineType: 'Build'
          #     BuildDefinition: 'dependent'
          #     Async: false
          
          # - task: TriggerPipeline@2
          #   inputs:
          #     serviceConnection: 'second-connection'
          #     project: 'e5edbb49-5652-4c20-906c-a0269b1c9c91'
          #     Pipeline: 'Build'
          #     buildDefinition: '3'
          #     Branch: 'main'
          #     buildapiversion: '5.1'