# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: ubuntu-latest

parameters:
- name: configs
  type: string
  values:
    - qa
    - dev
    - prod

trigger: none

jobs:
- ${{ if contains(parameters.configs, 'qa') }}:
  - job: x86
    steps:
    - script: echo Building x86...
- ${{ if contains(parameters.configs, 'dev') }}:
  - job: x64
    steps:
    - script: echo Building x64...
- ${{ if contains(parameters.configs, 'prod') }}:
  - job: arm
    steps:
    - script: echo Building arm...
