# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: ubuntu-latest

parameters:
- name: configs
  type: string
  values:
    - qa
    - dev
    - prod

trigger: none

jobs:
- ${{ if contains(parameters.configs, 'qa') }}:
  - job: qa
    steps:
    - script: echo qa.
- ${{ if contains(parameters.configs, 'dev') }}:
  - job: dev
    steps:
    - script: echo dev environment
- ${{ if contains(parameters.configs, 'prod') }}:
  - job: prod
    steps:
    - script: echo prod
